export const actionTypes = {
  MARK_TASK_COMPLETE: 'MARK_TASK_COMPLETE',
  MARK_TASK_INCOMPLETE: 'MARK_TASK_INCOMPLETE',
  SCHEDULE_TASK: 'SCHEDULE_TASK',
  UNSCHEDULE_TASK: 'UNSCHEDULE_TASK',
  DELETE_TASK: 'DELETE_TASK',
  UPDATE_TASK: 'UPDATE_TASK',
  LOAD_MORE_TASKS: 'LOAD_MORE_TASKS',
  CREATE_DRAFT_BODY: 'CREATE_DRAFT_BODY',
  CREATE_DRAFT_DATE: 'CREATE_DRAFT_DATE',
  DESTROY_DRAFT: 'DESTROY_DRAFT',
  CREATE_TASK: 'CREATE_TASK',
};
