export const actionTypes = {
  MARK_TASK_COMPLETE: 'MARK_TASK_COMPLETE',
  MARK_TASK_INCOMPLETE: 'MARK_TASK_INCOMPLETE',
  SCHEDULE_TASK: 'SCHEDULE_TASK',
  UNSCHEDULE_TASK: 'UNSCHEDULE_TASK',
  DELETE_TASK: 'DELETE_TASK',
  UPDATE_TASK: 'UPDATE_TASK',
  LOAD_MORE_TASKS: 'LOAD_MORE_TASKS',
};
