export const actionTypes = {
  MARK_TASK_COMPLETE: 'MARK_TASK_COMPLETE',
  MARK_TASK_UNCOMPLETE: 'MARK_TASK_UNCOMPLETE',
  SCHEDULE_TASK: 'SCHEDULE_TASK',
  UNSCHEDULE_TASK: 'UNSCHEDULE_TASK',
  DELETE_TASK: 'DELETE_TASK',
  UPDATE_TASK: 'UPDATE_TASK',
};
