export const CREATE_DRAFT_BODY = 'CREATE_DRAFT_BODY';
export const CREATE_DRAFT_DATE = 'CREATE_DRAFT_DATE';
export const DESTROY_DRAFT = 'DESTROY_DRAFT';
export const CREATE_TASK = 'CREATE_TASK';
export const UPDATE_TASK = 'UPDATE_TASK';
